/**
 * Copy slim SAM artifacts into data/sam/ for git commit or Docker bake.
 *   npm run sam:publish-data
 *
 * Fails (exit 1) if exclusions list is empty — avoids committing empty files.
 */
import fs from "node:fs/promises";
import { loadEnv } from "./env.js";
import {
  bundledEntityDbPath,
  bundledExclusionsPath,
  cacheEntityDbPath,
  cacheExclusionsJsonPath,
  dataSamDir,
} from "./samDataPaths.js";
import {
  ensureSamExclusionsIndex,
  getExcludedUeis,
  getSamExtractStatus,
} from "./samExtract.js";

loadEnv();

// Force re-download in CI when publishing (do not treat empty data/ as success)
if (process.env.CI === "true") {
  process.env.SAM_FORCE_DOWNLOAD = process.env.SAM_FORCE_DOWNLOAD ?? "1";
}

await fs.mkdir(dataSamDir(), { recursive: true });

const ex = await ensureSamExclusionsIndex();
const status = getSamExtractStatus();

let ueis = getExcludedUeis();
if (ueis.length === 0) {
  try {
    const raw = await fs.readFile(cacheExclusionsJsonPath(), "utf8");
    const parsed = JSON.parse(raw) as { ueis?: string[] };
    ueis = (parsed.ueis ?? []).map((u) => u.toUpperCase());
  } catch {
    /* empty */
  }
}

console.log(
  JSON.stringify(
    {
      exclusionsOk: ex.ok,
      exclusionsCount: ueis.length,
      source: status.source,
      error: ex.error,
      hasSamKey: Boolean(process.env.SAM_API_KEY?.trim()),
    },
    null,
    2,
  ),
);

if (ueis.length === 0) {
  console.error(`
SAM exclusions list is EMPTY. Nothing useful was written to data/sam/.

Most common causes:
  1. GitHub secret SAM_API_KEY is missing or wrong
     → Settings → Secrets and variables → Actions → SAM_API_KEY
  2. SAM daily quota (429) — wait until nextAccessTime, re-run the Action
  3. Download/parse failed — open the Action log step "Sync exclusions extract"

The workflow should fail (not commit an empty file).
`);
  process.exitCode = 1;
} else {
  const header = [
    "# SAM public exclusion UEIs (one per line).",
    `# Generated ${new Date().toISOString()}`,
    `# Count: ${ueis.length}`,
    "# Regenerated by: npm run sam:publish-data / GitHub Action sam-data.yml",
    "",
  ].join("\n");

  await fs.writeFile(
    bundledExclusionsPath(),
    header + ueis.sort().join("\n") + "\n",
    "utf8",
  );
  console.log(
    JSON.stringify(
      {
        exclusionsPath: bundledExclusionsPath(),
        exclusionsCount: ueis.length,
      },
      null,
      2,
    ),
  );
}

// Entity DB: copy from cache if present
try {
  await fs.access(cacheEntityDbPath());
  await fs.copyFile(cacheEntityDbPath(), bundledEntityDbPath());
  const st = await fs.stat(bundledEntityDbPath());
  console.log(
    JSON.stringify(
      {
        entityDbPath: bundledEntityDbPath(),
        entityDbBytes: st.size,
      },
      null,
      2,
    ),
  );
} catch {
  console.log(
    JSON.stringify({
      entityDbPath: bundledEntityDbPath(),
      entityDbCopied: false,
      note: "No entities.sqlite yet (run sam:sync-entities or use Release only).",
    }),
  );
}
