/**
 * Copy slim SAM artifacts into data/sam/ for git commit or Docker bake.
 *   npm run sam:publish-data
 */
import fs from "node:fs/promises";
import path from "node:path";
import { loadEnv } from "./env.js";
import {
  bundledEntityDbPath,
  bundledExclusionsPath,
  cacheEntityDbPath,
  cacheExclusionsJsonPath,
  dataSamDir,
} from "./samDataPaths.js";
import { ensureSamExclusionsIndex, getSamExtractStatus } from "./samExtract.js";

loadEnv();

await fs.mkdir(dataSamDir(), { recursive: true });

// Exclusions: prefer in-memory / cache JSON after ensure
const ex = await ensureSamExclusionsIndex();
const status = getSamExtractStatus();

let ueis: string[] = [];
if (status.count > 0) {
  // Reload from cache file for full list
  try {
    const raw = await fs.readFile(cacheExclusionsJsonPath(), "utf8");
    const parsed = JSON.parse(raw) as { ueis?: string[] };
    ueis = (parsed.ueis ?? []).map((u) => u.toUpperCase());
  } catch {
    /* empty */
  }
}

const header = [
  "# SAM public exclusion UEIs (one per line).",
  `# Generated ${new Date().toISOString()}`,
  `# Count: ${ueis.length}`,
  "# Regenerated by: npm run sam:publish-data / GitHub Action sam-data.yml",
  "",
].join("\n");

await fs.writeFile(
  bundledExclusionsPath(),
  header + ueis.sort().join("\n") + (ueis.length ? "\n" : ""),
  "utf8",
);
console.log(
  JSON.stringify(
    {
      exclusionsPath: bundledExclusionsPath(),
      exclusionsCount: ueis.length,
      exclusionsOk: ex.ok || ueis.length > 0,
    },
    null,
    2,
  ),
);

// Entity DB: copy from cache if present
try {
  await fs.access(cacheEntityDbPath());
  await fs.copyFile(cacheEntityDbPath(), bundledEntityDbPath());
  const st = await fs.stat(bundledEntityDbPath());
  console.log(
    JSON.stringify(
      {
        entityDbPath: bundledEntityDbPath(),
        entityDbBytes: st.size,
      },
      null,
      2,
    ),
  );
} catch {
  console.log(
    JSON.stringify({
      entityDbPath: bundledEntityDbPath(),
      entityDbCopied: false,
      note: "No .cache/sam/entities.sqlite yet. Run npm run sam:sync-entities first (or skip if using Release only).",
    }),
  );
}
